name: Docs

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and deploy documentation on GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANT: mandatory for GitHub Pages deployment
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: ">=0.6.0"
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Fetch gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages --depth=1 || echo "gh-pages branch does not exist"
      - name: Install documentation dependencies
        run: uv sync --group docs
      - name: Set default version
        working-directory: docs
        run: |
          if [[ -z "$(uv run mike list)" ]]; then
            uv run mike set-default --push --allow-undefined latest
          else
            echo "Skipping setting default."
          fi
      - name: Upload documentation site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: docs/build/html
      - name: Deploy "dev" version
        if: github.ref_name == 'main'
        working-directory: docs
        run: |
          uv run mike deploy --push dev
      - name: Deploy tagged version
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: docs
        run: |
          TAG=$(uv run python -c "print('.'.join('${{ github.ref_name }}'.split('.')[:2]))")
          uv run mike deploy --push --update-aliases $TAG latest
