name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build:
    name: Build and check distribution package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: ">=0.8.0"
      - name: Run build
        run: uv build
      - name: Run twine check
        run: uvx twine check dist/*
      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: py-dist
          path: dist/

  gh-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases
      id-token: write # IMPORTANT: mandatory for sigstore
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: py-dist
          path: dist/
      - name: Sign the distribution artifacts with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: ./dist/*
      - name: Create GitHub Release
        run: |
          ./scripts/get_latest_release_notes.py --github-release > notes.md
          gh release create "${{ github.ref_name }}" dist/* --target "${{ github.sha }}" --title "${{ github.ref_name }}" --notes-file notes.md

  docker-build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login with registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.IMAGE_REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Login with Docker Hub (EOEPCA)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.EOEPCA_DOCKERHUB_USER }}
          password: ${{ secrets.EOEPCA_DOCKERHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}
            eoepca/${{ env.IMAGE_NAME }}
          tags: |
            # set image tag
            type=raw,value=${{ env.IMAGE_TAG }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: mode=max
          sbom: true
          push: true
